### ISSUE TITLE
Set up possible with traefik as proxy with https?

### ISSUE THREAD

**Issue by decentral1se** [rojenzaman/amusewiki-docker#4]
I have traefik configured to use https only and for set up, i understand that we need to use http to log into the site to configure it?

is it possible to somehow set up the https automatically, somehow feeding the certs from traefik into amusewiki?

**Comment by decentral1se** [comment]
https://amusewiki.org/library/ssl-certificates-with-lets-encrypt

**Comment by decentral1se** [comment]
My current config (deploying with docker swarm):

```
---
version: "3.8"

services:
  app:
    image: rojen/amusewiki:package
    networks:
      - proxy
    volumes:
      - certs:/certs
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80"
        - "traefik.http.routers.${STACK_NAME}.rule=Host(`${DOMAIN}`${EXTRA_DOMAINS})"
        - "traefik.http.routers.${STACK_NAME}.entrypoints=web-secure"
        - "traefik.http.routers.${STACK_NAME}.tls.certresolver=${LETS_ENCRYPT_ENV}"
        - "coop-cloud.${STACK_NAME}.version=package+0.1.0"

  certs:
    image: humenius/traefik-certs-dumper:1.5
    volumes:
      - traefik_letsencrypt:/traefik
      - certs:/output
    environment:
      - ACME_FILE_PATH=/traefik/production-acme.json
      - DOMAIN=${DOMAIN}

volumes:
  certs:
  traefik_letsencrypt:
    name: "${TRAEFIK_SERVICE:-traefik_letsencrypt}"
    external: true

networks:
  proxy:
    external: true
```

Still seeing https://github.com/rojenzaman/amusewiki-docker/issues/3 as the error...
