### ISSUE TITLE
Possible to tag specific versions beyond "package"?

### ISSUE THREAD

**Issue by decentral1se** [rojenzaman/amusewiki-docker#5]
It's hard to know which exact version is being deployed with the "package" tag, could specific version numbers be tagged also?

Hard to tell just exactly a new package comes out tho?

- https://github.com/melmothx/amusewiki-debian-packages/commits/master

**Comment by rojenzaman** [comment]
Done: [rojen/amusewiki:package-2.551](https://hub.docker.com/layers/rojen/amusewiki/package-2.551/images/sha256-97333ca4ca7111b3e30dc0d83bd17779ee3ff1e498f7fb687166aa672fed1666?context=explore) / [actions](https://github.com/rojenzaman/amusewiki-docker/actions/runs/3101595429/jobs/5023117124)

I created a docker image named [amw_version](https://github.com/rojenzaman/amusewiki-docker/blob/master/package/Dockerfile.getversion) to get the version number of Amusewiki. When Github Actions is run, the amw_version image will be build and the version number can be assigned from amw_version container.

```yaml
    - name: Build the Docker image version
      run: docker build packages.amusewiki.org/ --file packages.amusewiki.org/Dockerfile.getversion --tag amw_version

    - name: Build the Docker image
      run: docker build packages.amusewiki.org/ --file packages.amusewiki.org/Dockerfile --tag rojen/amusewiki:latest --tag rojen/amusewiki:package --tag rojen/amusewiki:package-$(docker run amw_version) --build-arg AMW_WORKERS=5

    - name: Docker Push
      run: docker push rojen/amusewiki:package; docker push rojen/amusewiki:latest; docker push rojen/amusewiki:package-$(docker run amw_version)
```

I couldn't think of an easier way. Versioning is currently only possible for the package tag.

Is it enough?
